### ISSUE TITLE
how to use the little snitch .lsrules file?

### ISSUE THREAD

**Issue by sneak** [adversarialtools/apple-telemetry#19]
The documentation is lacking on this matter and I don't see an "import" option in LS 5.3.

**Comment by cedws** [comment]
Not sure, I don't use Little Snitch. @ThatIsAPseudo might be able to help.

**Comment by ThatIsAPseudo** [comment]
You can't "import" rules lists, you have to subscribe to it.
That's quite a shame because you can't choose a disk path nor provide a non-`https` url (which means no easy file self-serving through http://localhost, even though you can still use a reverse proxy or upload your list to pastebin/github)

To subscribe to a list :
![img1](https://user-images.githubusercontent.com/17936055/163224634-796019fb-0827-498a-857c-780c15e06223.png)
![img2](https://user-images.githubusercontent.com/17936055/163224720-3bf5c79e-6d02-478a-a0b3-749276c13acd.png)
![img3](https://user-images.githubusercontent.com/17936055/163224736-c1b8d8ee-f1cb-4629-afec-ca0d49d675e3.png)

**Comment by cedws** [comment]
I see, cheers.
